export const indicatorsCodesJson: { [key: string]: string } = {
	['Inflation']: 'FP.CPI.TOTL.ZG',
	['GDP']: 'NY.GDP.MKTP.CD',
	['Population']: 'SP.POP.TOTL',
	['Poverty Headcount Ratio']: 'SI.POV.DDAY',
	['Cause of death by injury (% of total)']: 'SH.DTH.INJR.ZS',
	['Arable land (hectares per person)']: 'AG.LND.ARBL.HA.PC',
	["Average precipitation in depth (mm per year)"]: "AG.LND.PRCP.MM",
	["Forest area (% of land area)"]: "AG.LND.FRST.ZS",
	["Land area (sq. km)"]: 'AG.LND.TOTL.K2',
	["Prevalence of HIV, total (% of ages 15-49)"]: 'SH.DYN.AIDS.ZS',
	["Probability of dying among youth ages 20-24 years (per 1,000)"]: "SH.DYN.2024",
	["Probability of dying among adolescents ages 10-14 years (per 1,000)"]: "SH.DYN.1014",
	["Probability of dying among children ages 5-9 years (per 1,000)"]: "SH.DYN.0509",
	["Mortality rate, under-5, male (per 1,000 live births)"]: "SH.DYN.MORT.MA",
	["Mortality rate, under-5, female (per 1,000 live births)"]: "SH.DYN.MORT.FE",
	["Access to electricity (% of population)"]: "EG.ELC.ACCS.ZS",
	["CO2 emissions (metric tons per capita)"]: "EN.ATM.CO2E.PC",
	["Electric power consumption (kWh per capita)"]: "EG.USE.ELEC.KH.PC",
	["Urban population"]: "SP.URB.TOTL",
	["CO2 emissions (kt)"]: "EN.ATM.CO2E.KT",
	["Exports of goods and services (% of GDP)"]: "NE.EXP.GNFS.ZS",
	["Imports of goods and services (% of GDP)"]: "NE.IMP.GNFS.ZS",
}